url: http://farmtofork.com
title: Farm to Fork Farmers Market
subtitle: at Normandy Farms
author: Friends of the Green Market
simple_search: http://google.com/search

# From https://help.github.com/articles/using-jekyll-with-pages
safe: true
lsi: false
pygments: true

permalink: /blog/:year/:month/:day/:title
paginate: 5

exclude:
  - Gemfile
  - Gemfile.lock
  - .bundle
  - bin
  - vendor
