url: http://farmtofork.com
title: Farm to Fork Market
subtitle: at Normandy Farms
author: Friends of the Green Market
simple_search: http://google.com/search

keywords:
- Indianapolis farmers market
- Northwest Indianapolis farmers market
- winter farmers market
- Farm to Fork Market
- farmers market
- organic farmers market
- chemical free farmers market
- Normandy Farm

# For cache busting
asset_version: 1

# From https://help.github.com/articles/using-jekyll-with-pages
safe: true
lsi: false
pygments: true

paginate: 5

exclude:
  - .ruby-version
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - .bundle
  - bin
  - params.json
  - vendor
  - swatches.html
